# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/steve/projects/DifferenceFormatter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/steve/projects/DifferenceFormatter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steve/projects/DifferenceFormatter/CMakeFiles /home/steve/projects/DifferenceFormatter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steve/projects/DifferenceFormatter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DifferenceFomatter

# Build rule for target.
DifferenceFomatter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DifferenceFomatter
.PHONY : DifferenceFomatter

# fast build rule for target.
DifferenceFomatter/fast:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/build
.PHONY : DifferenceFomatter/fast

DifferenceFormatter.o: DifferenceFormatter.cpp.o
.PHONY : DifferenceFormatter.o

# target to build an object file
DifferenceFormatter.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceFormatter.cpp.o
.PHONY : DifferenceFormatter.cpp.o

DifferenceFormatter.i: DifferenceFormatter.cpp.i
.PHONY : DifferenceFormatter.i

# target to preprocess a source file
DifferenceFormatter.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceFormatter.cpp.i
.PHONY : DifferenceFormatter.cpp.i

DifferenceFormatter.s: DifferenceFormatter.cpp.s
.PHONY : DifferenceFormatter.s

# target to generate assembly for a file
DifferenceFormatter.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceFormatter.cpp.s
.PHONY : DifferenceFormatter.cpp.s

DifferenceFormatterApp.o: DifferenceFormatterApp.cpp.o
.PHONY : DifferenceFormatterApp.o

# target to build an object file
DifferenceFormatterApp.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceFormatterApp.cpp.o
.PHONY : DifferenceFormatterApp.cpp.o

DifferenceFormatterApp.i: DifferenceFormatterApp.cpp.i
.PHONY : DifferenceFormatterApp.i

# target to preprocess a source file
DifferenceFormatterApp.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceFormatterApp.cpp.i
.PHONY : DifferenceFormatterApp.cpp.i

DifferenceFormatterApp.s: DifferenceFormatterApp.cpp.s
.PHONY : DifferenceFormatterApp.s

# target to generate assembly for a file
DifferenceFormatterApp.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceFormatterApp.cpp.s
.PHONY : DifferenceFormatterApp.cpp.s

DifferenceParser.o: DifferenceParser.cpp.o
.PHONY : DifferenceParser.o

# target to build an object file
DifferenceParser.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceParser.cpp.o
.PHONY : DifferenceParser.cpp.o

DifferenceParser.i: DifferenceParser.cpp.i
.PHONY : DifferenceParser.i

# target to preprocess a source file
DifferenceParser.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceParser.cpp.i
.PHONY : DifferenceParser.cpp.i

DifferenceParser.s: DifferenceParser.cpp.s
.PHONY : DifferenceParser.s

# target to generate assembly for a file
DifferenceParser.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceParser.cpp.s
.PHONY : DifferenceParser.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DifferenceFomatter"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DifferenceFormatter.o"
	@echo "... DifferenceFormatter.i"
	@echo "... DifferenceFormatter.s"
	@echo "... DifferenceFormatterApp.o"
	@echo "... DifferenceFormatterApp.i"
	@echo "... DifferenceFormatterApp.s"
	@echo "... DifferenceParser.o"
	@echo "... DifferenceParser.i"
	@echo "... DifferenceParser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

