# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/steve/projects/DifferenceFormatter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/steve/projects/DifferenceFormatter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steve/projects/DifferenceFormatter/CMakeFiles /home/steve/projects/DifferenceFormatter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steve/projects/DifferenceFormatter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DifferenceFomatter

# Build rule for target.
DifferenceFomatter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DifferenceFomatter
.PHONY : DifferenceFomatter

# fast build rule for target.
DifferenceFomatter/fast:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/build
.PHONY : DifferenceFomatter/fast

CodeLine.o: CodeLine.cpp.o
.PHONY : CodeLine.o

# target to build an object file
CodeLine.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/CodeLine.cpp.o
.PHONY : CodeLine.cpp.o

CodeLine.i: CodeLine.cpp.i
.PHONY : CodeLine.i

# target to preprocess a source file
CodeLine.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/CodeLine.cpp.i
.PHONY : CodeLine.cpp.i

CodeLine.s: CodeLine.cpp.s
.PHONY : CodeLine.s

# target to generate assembly for a file
CodeLine.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/CodeLine.cpp.s
.PHONY : CodeLine.cpp.s

Difference.o: Difference.cpp.o
.PHONY : Difference.o

# target to build an object file
Difference.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/Difference.cpp.o
.PHONY : Difference.cpp.o

Difference.i: Difference.cpp.i
.PHONY : Difference.i

# target to preprocess a source file
Difference.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/Difference.cpp.i
.PHONY : Difference.cpp.i

Difference.s: Difference.cpp.s
.PHONY : Difference.s

# target to generate assembly for a file
Difference.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/Difference.cpp.s
.PHONY : Difference.cpp.s

DifferenceFormatterApp.o: DifferenceFormatterApp.cpp.o
.PHONY : DifferenceFormatterApp.o

# target to build an object file
DifferenceFormatterApp.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceFormatterApp.cpp.o
.PHONY : DifferenceFormatterApp.cpp.o

DifferenceFormatterApp.i: DifferenceFormatterApp.cpp.i
.PHONY : DifferenceFormatterApp.i

# target to preprocess a source file
DifferenceFormatterApp.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceFormatterApp.cpp.i
.PHONY : DifferenceFormatterApp.cpp.i

DifferenceFormatterApp.s: DifferenceFormatterApp.cpp.s
.PHONY : DifferenceFormatterApp.s

# target to generate assembly for a file
DifferenceFormatterApp.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceFormatterApp.cpp.s
.PHONY : DifferenceFormatterApp.cpp.s

DifferenceSet.o: DifferenceSet.cpp.o
.PHONY : DifferenceSet.o

# target to build an object file
DifferenceSet.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceSet.cpp.o
.PHONY : DifferenceSet.cpp.o

DifferenceSet.i: DifferenceSet.cpp.i
.PHONY : DifferenceSet.i

# target to preprocess a source file
DifferenceSet.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceSet.cpp.i
.PHONY : DifferenceSet.cpp.i

DifferenceSet.s: DifferenceSet.cpp.s
.PHONY : DifferenceSet.s

# target to generate assembly for a file
DifferenceSet.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/DifferenceSet.cpp.s
.PHONY : DifferenceSet.cpp.s

FileDifference.o: FileDifference.cpp.o
.PHONY : FileDifference.o

# target to build an object file
FileDifference.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/FileDifference.cpp.o
.PHONY : FileDifference.cpp.o

FileDifference.i: FileDifference.cpp.i
.PHONY : FileDifference.i

# target to preprocess a source file
FileDifference.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/FileDifference.cpp.i
.PHONY : FileDifference.cpp.i

FileDifference.s: FileDifference.cpp.s
.PHONY : FileDifference.s

# target to generate assembly for a file
FileDifference.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/FileDifference.cpp.s
.PHONY : FileDifference.cpp.s

Line.o: Line.cpp.o
.PHONY : Line.o

# target to build an object file
Line.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/Line.cpp.o
.PHONY : Line.cpp.o

Line.i: Line.cpp.i
.PHONY : Line.i

# target to preprocess a source file
Line.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/Line.cpp.i
.PHONY : Line.cpp.i

Line.s: Line.cpp.s
.PHONY : Line.s

# target to generate assembly for a file
Line.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/Line.cpp.s
.PHONY : Line.cpp.s

UnifiedDifferenceFile.o: UnifiedDifferenceFile.cpp.o
.PHONY : UnifiedDifferenceFile.o

# target to build an object file
UnifiedDifferenceFile.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/UnifiedDifferenceFile.cpp.o
.PHONY : UnifiedDifferenceFile.cpp.o

UnifiedDifferenceFile.i: UnifiedDifferenceFile.cpp.i
.PHONY : UnifiedDifferenceFile.i

# target to preprocess a source file
UnifiedDifferenceFile.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/UnifiedDifferenceFile.cpp.i
.PHONY : UnifiedDifferenceFile.cpp.i

UnifiedDifferenceFile.s: UnifiedDifferenceFile.cpp.s
.PHONY : UnifiedDifferenceFile.s

# target to generate assembly for a file
UnifiedDifferenceFile.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/UnifiedDifferenceFile.cpp.s
.PHONY : UnifiedDifferenceFile.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/DifferenceFomatter.dir/build.make CMakeFiles/DifferenceFomatter.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DifferenceFomatter"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CodeLine.o"
	@echo "... CodeLine.i"
	@echo "... CodeLine.s"
	@echo "... Difference.o"
	@echo "... Difference.i"
	@echo "... Difference.s"
	@echo "... DifferenceFormatterApp.o"
	@echo "... DifferenceFormatterApp.i"
	@echo "... DifferenceFormatterApp.s"
	@echo "... DifferenceSet.o"
	@echo "... DifferenceSet.i"
	@echo "... DifferenceSet.s"
	@echo "... FileDifference.o"
	@echo "... FileDifference.i"
	@echo "... FileDifference.s"
	@echo "... Line.o"
	@echo "... Line.i"
	@echo "... Line.s"
	@echo "... UnifiedDifferenceFile.o"
	@echo "... UnifiedDifferenceFile.i"
	@echo "... UnifiedDifferenceFile.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

