function(COPY_BINARIES __PROJECT __BASENAME __BIN_DIRECTORY)
	file(MAKE_DIRECTORY ${__BIN_DIRECTORY})
	foreach(EXTENSION ${ARGN})
		if ("${EXTENSION}" STREQUAL "_")
			set(FILENAME ${__BASENAME})
		else()
			set(FILENAME ${__BASENAME}.${EXTENSION})
		endif()
		set(SOURCE_PATH ${BUILD_DIRECTORY}/${FILENAME})
		set(DESTINATION_PATH ${__BIN_DIRECTORY}/${FILENAME})
		message(STATUS "Adding copy step ${SOURCE_PATH} -> ${DESTINATION_PATH}")
		add_custom_command(
			TARGET ${__PROJECT}
			POST_BUILD
			COMMAND "${CMAKE_COMMAND}"
			ARGS -E copy_if_different ${SOURCE_PATH} ${DESTINATION_PATH}
			COMMENT "Copying ${FILENAME} to bin directory")
	endforeach(EXTENSION)
endfunction(COPY_BINARIES)

function(COPY_LIBRARY __TARGET __BIN_DIRECTORY)
	if (WIN32)
		COPY_BINARIES(${__TARGET} ${__TARGET} ${__BIN_DIRECTORY} dll)
	else (UNIX)
		COPY_BINARIES(${__TARGET} lib${__TARGET} ${__BIN_DIRECTORY} so)
	endif()
endfunction(COPY_LIBRARY)

function(COPY_EXECUTABLE __TARGET __BIN_DIRECTORY)
	if (WIN32)
		COPY_BINARIES(${__TARGET} ${__TARGET} ${__BIN_DIRECTORY} exe)
	else (UNIX)
		COPY_BINARIES(${__TARGET} ${__TARGET} ${__BIN_DIRECTORY} _)
	endif()
endfunction(COPY_EXECUTABLE)
