function(COPY_INCLUDES __EXPORTED_FILES INCLUDE_PATH)
	file(MAKE_DIRECTORY ${INCLUDE_PATH})
	set(COPIED_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ)
	set(${__EXPORTED_FILES})
	foreach(HEADER ${ARGN})
		set(SOURCE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/${HEADER})
		set(DESTINATION_PATH ${INCLUDE_PATH}/${HEADER})
		message(STATUS "Adding copy step ${SOURCE_PATH} -> ${DESTINATION_PATH}")
		list(APPEND ${__EXPORTED_FILES} ${DESTINATION_PATH})
		add_custom_command(
			OUTPUT ${DESTINATION_PATH}
			COMMAND "${CMAKE_COMMAND}"
			ARGS -E copy_if_different ${SOURCE_PATH} ${DESTINATION_PATH}
			DEPENDS ${HEADER}
			COMMENT "Copying ${HEADER} to include directory"
			VERBATIM )
	endforeach(HEADER)
	set(${__EXPORTED_FILES} ${${__EXPORTED_FILES}} PARENT_SCOPE)
endfunction(COPY_INCLUDES)
